baseURL: "https://www.carlobloks.com/"
title: Carlo Bloks 😎
paginate: 5
theme: papermod
enableInlineShortcodes: true
enableRobotsTXT: true

minify:
    disableXML: true
    # minifyOutput: true

languages:
    en:
        languageName: "English"
        weight: 1
        menu:
            main:
                - name: About Me
                  url: about/
                  weight: 5
                - name: Resume
                  url: resume/
                  weight: 10
                - name: Booklist
                  url: blog/booklist-2021/
                  weight: 15
outputs:
    home:
        - HTML
        - RSS
        - JSON

params:
    env: production
    description: "This is my personal website. I'll share some of my interest as well as what I am currently working on. Feel free to reach out 🚀"
    # author: ["Me", "You"] # multiple authors
    ShowReadingTime: false
    defaultTheme: dark
    ShowShareButtons: false
    displayFullLangName: true
    images: ["/opengraph.png"]
    # assets:
    #   favicon: '<path / external url>'

    profileMode:
        enabled: false
        title: Carlo Bloks
        imageUrl: "#"
        imageTitle: my image
        # imageWidth: 120
        # imageHeight: 120
        buttons:
            - name: Archives
              url: archives
            - name: Tags
              url: tags

    homeInfoParams:
        Title: "Hi \U0001F44B"
        Content: >
            My name is Carlo and I am a **Freelance Product Owner / Digital Experience Manager** and constantly seeking new things to learn

        Content2: >
            > Some of those things I'll share here...

    socialIcons:
        - name: linkedin
          url: "https://www.linkedin.com/in/carlobloks"
        - name: github
          url: "https://github.com/gcb2018/"
        - name: other
          url: "/resume/"

taxonomies:
    category: categories
    tag: tags
    series: series