[build]
  publish = "public"
  command = "hugo"

[context.production.environment]
  HUGO_VERSION = "0.79.0"
  HUGO_ENV = "production"
  HUGO_ENABLEGITINFO = "true"
  
[context.branch-deploy.environment]
  HUGO_VERSION = "0.79.0"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.79.0"
  
[context.deploy-preview]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[context.branch-deploy]
  command = "hugo -b $DEPLOY_PRIME_URL --buildFuture"

[[redirects]]
  from = "http://localhost:1313/blog/story-mapping-in-short"
  to = "/blog/story-discovery-in-short"
  status = 301
  force = true

[[redirects]]
  from = "https://carlobloks.netlify.app/*"
  to = "https://www.carlobloks.com/:splat"
  status = 301
  force = true #COMMENT: ensure that we always redirect